#!/bin/bash

make clean > /dev/null
make -j4
INPUT=`find ./tests/files -xtype f -iname *.pas`
for i in $INPUT; do
    echo '===================================================================================='
    echo compile with mine:
    echo ./out $i
    ./out $i
    code=$?
    if [ $code -ne  0 ]; then
        echo "Compiler died."
        exit 1
    fi
    echo compile with komp:
    echo ./tests/komp $i ./tests/original.asm
    ./tests/komp $i ./tests/original.asm

    mine=`./tests/vm ./output.asm`
    komp=`./tests/vm ./tests/original.asm`
    if [ "$mine" != "$komp" ]; then
        echo ERROR IN TEST!
        echo Mine:
        echo $mine
        echo original:
        echo $komp
        exit 1
    else
        echo $mine
        echo $komp
        echo NO DIFF
    fi

done
rm -f ./tests/original.asm
make clean
make headers
exit 0