#!/bin/bash

make -j4
valgrind='valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1'
if [ $# -ne 0 ]; then
    INPUT=$@
else
    INPUT=`find ./tests/files -xtype f -iname *.pas`
fi
for i in $INPUT; do
    echo '===================================================================================='
    echo compile with mine + valgrind:
    echo $valgrind ./out $i
    $valgrind ./out $i
    code=$?
    if [ $code -ne  0 ]; then
        echo "Valgrind says there are leaks or compiler died."
        exit 1
    fi
    echo compile with komp:
    echo ./tests/komp $i ./tests/original.asm
    ./tests/komp $i ./tests/original.asm

    mine=`./tests/vm ./output.asm`
    komp=`./tests/vm ./tests/original.asm`
    if [ "$mine" != "$komp" ]; then
        echo ERROR IN TEST!
        echo Mine:
        echo $mine
        echo original:
        echo $komp
        exit 1
    else
        echo $mine
        echo $komp
        echo NO DIFF
    fi

done
rm -f ./tests/original.asm
make clean
make headers
exit 0